# Generated by Django 3.1.4 on 2021-08-07 07:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('Priority', models.CharField(choices=[('h', 'high'), ('l', 'low')], max_length=4)),
                ('task_text', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            managers=[
                ('task', django.db.models.manager.Manager()),
            ],
        ),
    ]
